if(EXISTS "D:/Projects/SecondEngineProject/TestProjects/3DTest/EngineBuild/EngineTests[1]_tests.cmake")
  include("D:/Projects/SecondEngineProject/TestProjects/3DTest/EngineBuild/EngineTests[1]_tests.cmake")
else()
  add_test(EngineTests_NOT_BUILT EngineTests_NOT_BUILT)
endif()
